### ISSUE TITLE
Implement (weighted) interval score

### ISSUE THREAD

**Issue by frazane** [frazane/scoringrules#3]
References:
- Gneiting T, Raftery AE. Strictly proper scoring rules, prediction, and estimation. J Am Stat Assoc. 2007;102(477):359–378
- Bracher J, Ray EL, Gneiting T, Reich NG (2022) Correction: Evaluating epidemic forecasts in an interval format. PLOS Computational Biology 18(10): e1010592

**Comment by simon-hirsch** [comment]
Then let's continue with this one: Question about the API: do we want a forecast array that is (n x 2 x a) where alpha is the length of the $\alpha$ vector or do we want to have `upper` and `lower` parameters? Or both? 

I was thinking about somehting like this:
```
def winkler(obs, lower, upper, alpha, backend=None):
    """Winkler or Interval Score for prediction interval PI[lower, upper] and observations."""
    B = backends.active if backend is None else backends[backend]
    width = upper - lower
    inside = (obs[:, None] >= lower) & (obs[:, None] <= upper)
    above = (obs[:, None] > upper)
    below = (obs[:, None] < lower)
    W = (
        below * width + (2 / alpha) * (lower - obs[:, None]) +
        inside * width + 
        above * width + (2 / alpha) * (obs[:, None] - upper)
    )
    return B.mean(W, axis=-1)
```

**Comment by frazane** [comment]
I'd call it `interval_score` since it's based on intervals :smile:, and then mention Winkler in the docs. 

About the API...good question. I worked a bit on this a while a go but wasn't sure about the best way to go. If I remember correctly, I had something like `lower = (n, a)`, `upper=(n, a)` and `alpha=(a,)`. That's a good solution for now. 

My idea was to also have an additional keyword argument for the weights given to each interval.

**Comment by simon-hirsch** [comment]
There are probably more scoring functions for PIs than the Winkler Score only 😅 your call though :)

All right, then I'll go with the upper, lower, alpha and weights and will implement a first draft 👍🏽

**Comment by frazane** [comment]
> There are probably more scoring functions for PIs than the Winkler Score only 😅 your call though :)

You are right, but as far as I know it's by far the most popular denomination in the literature. I've rarely seen "Winkler score" alone but more commonly "Winkler interval score" or similar so we could go with that (`interval_score_winkler`, `interval_score_xxx`, etc.) :slightly_smiling_face:  What's important for me is that we also include "interval score" in the function name because it's sort of self-explanatory for users. What do you think?
